on:
  push:
    branches: [main]
  schedule:
    - cron: '*/30 * * * *'
  workflow_dispatch:

jobs:
  reefer:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      issues: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Deno
        uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x

      - name: Run
        run: deno run --allow-net --allow-read --allow-env --allow-ffi https://raw.githubusercontent.com/zerogram-dev/reefer/refs/heads/main/src/main.ts
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          REPO: ${{ github.repository }}
          TRACKING_ISSUE_NO: 2
